#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=16
#SBATCH --ntasks=1024
#SBATCH --ntasks-per-node=64
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:10:00
#SBATCH --partition=dc-cpu

srun python aamain.py >> aaresults.out
touch ready
