#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=outtt
#SBATCH --error=errr
#SBATCH --time=00:05:00
#SBATCH --partition=batch

srun python mainnn.py
