#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=16
#SBATCH --output=outt
#SBATCH --error=err
#SBATCH --time=00:05:00
#SBATCH --partition=batch

srun python mainn.py
