#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=4
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=16
#SBATCH --output=out
#SBATCH --error=er
#SBATCH --time=00:05:00
#SBATCH --partition=batch

srun python main.py
