#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=2
#SBATCH --ntasks=32
#SBATCH --ntasks-per-node=16
#SBATCH --output=outtt
#SBATCH --error=errr
#SBATCH --time=00:05:00
#SBATCH --partition=batch

srun python mainnn.py
