#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --ntasks-per-node=12
#SBATCH --output=mpi-out
#SBATCH --error=mpi-err
#SBATCH --time=00:10:00
#SBATCH --partition=batch

srun python main.py
