#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=8
#SBATCH --ntasks=512
#SBATCH --ntasks-per-node=64
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:10:00
#SBATCH --partition=dc-cpu

srun python boltzmann1.py --proc_col=16 >> results1
