#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=6
#SBATCH --ntasks=384
#SBATCH --ntasks-per-node=64
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:20:00
#SBATCH --partition=dc-cpu

srun python boltzmann3.py --time_intervals=16 >> results3
