#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=2
#SBATCH --ntasks=96
#SBATCH --ntasks-per-node=48
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:20:00
#SBATCH --partition=dc-cpu

srun python boltzmann3.py --time_intervals=4 >> results3
