#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=4
#SBATCH --ntasks=256
#SBATCH --ntasks-per-node=64
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=01:00:00
#SBATCH --partition=dc-cpu

srun python boltzmann1.py >> results.out