#!/bin/bash -x
#SBATCH --account=cstma
#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=64
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:05:00
#SBATCH --partition=dc-cpu

srun python ac_newton.py  --time_intervals=64 --rolling=1 >> results_newton.out